pockets/urls.py
from django.urls import path


from pockets.views import (
    pocket_delete_view,
    pocket_detail_view,
    api_pocket_list_view,
    pocket_create_view,
    full_pocket_delete_view,
 
)
# has api/pockets before each endpoint
urlpatterns = [
    path('full/delete', full_pocket_delete_view, name="full pocket del"),
    path('<int:pocket_id>/delete', pocket_delete_view),
    path('<int:pocket_id>', pocket_detail_view),
    path('pocketcreate', pocket_create_view),
    path('', api_pocket_list_view),   


]

pockets/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
User = settings.AUTH_USER_MODEL


class Pocket(models.Model):
    POCKET_CATEGORY = (
        ('Futures', 'Futures'),
        ('Cryptocurrency', 'Cryptocurrency'),
        ('FXCurrency', 'FXCurrency'),

        ('NFT Valuation', 'NFT Valuation'),
        ('Stock','Stock'),
        ('Fund Allocation','Fund Allocation')

    )
    CURRENCY_TYPE = (
        ('USD', 'USD'),

    )
    DIRECTION = (
        ('NFT Valuation', 'NFT Valuation'),
        ('Short', 'Short'),
        ('Long', 'Long'),
        ('Fund Allocation','Fund Allocation')



    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=20,blank=True, null=True, verbose_name= ('Title'))
    exchange = models.CharField(max_length=20,blank=True, null=True, verbose_name= ('Exchange'))
    
    summary  = models.TextField(max_length=200,blank=True, null=True, verbose_name= ('Description'))
    price = models.DecimalField(max_digits=10, decimal_places=2 , verbose_name= ('Current Value'))
    # Price refelcts the Trades Profit or Loss 
    cost_basis = models.DecimalField(max_digits=10, decimal_places=2 , null=True, verbose_name= ('Cost Basis'))
    profit_or_loss = models.DecimalField(max_digits=10, decimal_places=2 , null=True, verbose_name= ('Trade Profit or Loss'))
    
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name=('Date of Creation'))
    pocket_time_instance = models.DateField(auto_now_add=False, verbose_name=('Date of Trade'))
    category = models.CharField(max_length=40, choices=POCKET_CATEGORY, default='Spot Trade', verbose_name= ('Category'))
    direction = models.CharField(max_length=20, choices=DIRECTION, default='Long', verbose_name= ('Direction'))
    receipt = models.ImageField(upload_to='receipt/%Y/%m/%d/', default='firstImageEntry.svg', null=True, blank=True)
    currency = models.CharField(blank=True, null=True, max_length=10, choices=CURRENCY_TYPE, default='USD', verbose_name= ('currency'))


# Create your models here.
    
    # class Meta:
    #     ordering = ['-price']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('auth_home') 

pockets/forms.py
import django_filters
from django import forms
from .models import Pocket
from profiles.models import Profile

from django.conf import settings
from crispy_forms.helper import FormHelper

MAX_TITLE_LENGTH = settings.MAX_TITLE_LENGTH
MAX_SUMMARY_LENGTH = settings.MAX_SUMMARY_LENGTH

class ProfileFilter(django_filters.FilterSet):
    class Meta:
        model = Profile
        fields = ['user__username', 'user__first_name', 'user__last_name']


class PocketFilter(django_filters.FilterSet):
    class Meta:
        model = Pocket
        fields = ['title', 'summary', 'price', 'category', 'direction']
    # no need to query prices
    def get_title(self, obj):
        return obj.title

    def get_price(self, obj):
        return obj.price

    def get_category(self, obj):
        return obj.category
        
    def get_direction(self, obj):
        return obj.direction

    def get_summary(self, obj):
        return obj.summary

pockets/views.py
import json
import requests

from decimal import Decimal
from requests import Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects



from django.shortcuts import render, redirect
from django.db.models import F
from django.db.models import Q
from django import forms
from django.contrib.admin.widgets import AdminDateWidget


from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.decorators import api_view, permission_classes, authentication_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import SessionAuthentication 

from django.views.generic import UpdateView
from django.contrib import messages
from django.http import Http404, JsonResponse

from .serializers import (PocketSerializer, PocketCreateSerializer)
from profiles.models import Profile
from .models import Pocket
from .forms import PocketFilter, ProfileFilter
from django.conf import settings


ALLOWED_HOSTS = settings.ALLOWED_HOSTS

class PocketRemodel(UpdateView):# CBV Generic Pocket Update
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticated]
    model = Pocket
    
    template_name = "pockets/change.html"
    fields = ["title", "exchange", "summary", "cost_basis", "price", "category", "pocket_time_instance", "receipt", "currency", "direction"]
    proxy = model.objects.all()

 
    def get_context_data(self, **kwargs):
        context = super(PocketRemodel, self).get_context_data(**kwargs)
        pockets = Pocket.objects.filter(id=self.kwargs['pk'])

        context.update({
          'pocket_image': pockets.first().receipt,
          'pocket_PnL': pockets.first().profit_or_loss
          
          })
        return context

    def form_valid(self, form):
        # print the clean form to confirm
  
        return super().form_valid(form)


class ChartData(APIView):
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticated]

    def get(self, request, format=None):
        profile = Profile.objects.filter(user=request.user)
        pockets = Pocket.objects.filter(user=request.user).order_by(str(profile.first().order_matrix))

        magnify_profile = profile.first()
        bin = []
        labels = []
        sum_label_insert = []
        sum_bin_insert = []

        dynamicLineColorArray = [] # LINE CHART ARRAY with the color fo the sum inserted at start of array
        dynamicPriceToColorArray = [] # ARRAY OF THE CORRESPONDING COLORS
        hoverdynamicPriceToColorArray = []
        dynamicPercentArray = [] # PERCENTAGE ARRAY FOR ALLOCATION DOUGHNUT
        dynamicPreConversionPercentArray = [] # PERCENTAGE ARRAY FOR ALLOCATION DOUGHNUT


        satchel = Decimal(0.0)
        pos_satchel = Decimal(0.0)
        neg_satchel = Decimal(0.0)
        absoluteSatchel = Decimal(0.0)

        for proxy in pockets:
            absoluteSatchel += abs(proxy.price)

        for p in pockets:

            p.profit_or_loss = p.price-p.cost_basis
            p.save()
            dynamicPreConversionPercentArray.insert(0, round((abs(p.price)/int(absoluteSatchel))*100, 2))
            if p.currency == "USD":
                p.price = p.price * 1 

   


            if p.price >= 0:
                dynamicPriceToColorArray.insert(0,'rgba(80, 196, 74, 0.9)')
                hoverdynamicPriceToColorArray.insert(0,'rgba(80, 196, 74, 0.7)')
                dynamicLineColorArray.insert(0,'rgba(80, 196, 74, 0.9)')  
            elif p.price < 0:
                dynamicPriceToColorArray.insert(0,'rgba(255, 40, 40, 1)')
                hoverdynamicPriceToColorArray.insert(0,'crimson')
                dynamicLineColorArray.insert(0,'rgba(255, 40, 40, 1)')


 
            bin.insert(0, p.price)
            labels.insert(0, p.title)
            satchel += p.price # SUM of everything
            dynamicPercentArray.insert(0, round((abs(p.price)/int(absoluteSatchel))*100, 2))
                         

            sum_label_insert.insert(0, p.title)
            sum_bin_insert.insert(0, p.price)
            
            # Percentage Algorithm 

            if p.price < 0:
                neg_satchel += p.price 
            elif p.price >= 0:
                pos_satchel += p.price
        sum_label_insert.insert(len(sum_bin_insert), "TOTAL SUM")
        sum_bin_insert.insert(len(sum_bin_insert), satchel)
        if satchel >= 0:
            dynamicLineColorArray.insert(0,'rgba(16, 151, 16, 0.9)')  
        else:
            dynamicLineColorArray.insert(0,'rgba(255, 40, 40, 0.8)')
  
        
        profile.update(satchel = satchel)
        profile.update(pos_satchel = pos_satchel)
        profile.update(neg_satchel = neg_satchel)
 
        data = {
            "dynamicPreConversionPercentArray": dynamicPreConversionPercentArray,
            "dynamicPercentArray": dynamicPercentArray,
            "dynamicRBGArray": dynamicPriceToColorArray,
            "hoverdynamicRBGArray": hoverdynamicPriceToColorArray,
            "dynamicLineRBGArray": dynamicLineColorArray,
            "labels": labels,
            "default": bin,
            "satchel": magnify_profile.satchel,
            "labelInsertArray": sum_label_insert,
            "sumInsertArray": sum_bin_insert,
        } 
        return JsonResponse(data)





class AuthMaster(forms.Form):

    
    date_input = forms.DateField(widget=AdminDateWidget())
    receipt = forms.ImageField()
    currency = forms.ChoiceField()


    def index(request,  *args, **kwargs): # Main Page for Authenticated Users
        if not request.user.is_authenticated:
            return redirect('/oauth/login')
                
        profile_qs = Profile.objects.filter(user=request.user)
        oneqs = profile_qs.first()
        user_order_matrix = oneqs.order_matrix        
        pockets = Pocket.objects.filter(user=request.user)
        form = AuthMaster()
        for p in pockets:
            p.profit_or_loss = p.price-(p.cost_basis)
            p.save()
            

        context={

            "form": form,
            "user_order_matrix": user_order_matrix,
            "pockets_amount": pockets.count(),
            "profiles":profile_qs,
            "requested_users_pockets": pockets.all(),

            "satchel_amount": oneqs.satchel,
        }    

        return render(request, "pages/authpockets.html", context, status=200)




def listmode_view(request, *args, **kwargs): # template for profile detail

    pockets = Pocket.objects.filter(user=request.user)

    context = {
      "pockets_amount": pockets.count(),
      "requested_users_pockets": pockets.all(),
    }
    return render(request, "pockets/listmode.html", context)

@api_view(['POST'])
@authentication_classes([SessionAuthentication])
@permission_classes([IsAuthenticated])
def pocket_create_view(request, *args, **kwargs): # Creation of Pocket
    serializer = PocketCreateSerializer(data=request.POST)
    if serializer.is_valid(raise_exception=True):
        serializer.save(user=request.user)
        return Response(serializer.data, status=201)

    return Response({}, status=400)


# Authorized Profile View 
@api_view(['GET'])
@authentication_classes([SessionAuthentication])
@permission_classes([IsAuthenticated])
def pocket_detail_view(request, pocket_id, *args, **kwargs): # Pocket Detail ENDPOINT
    qs = Pocket.objects.filter(id=pocket_id)
    if not qs.exists():
        return Response({}, status=404)
    if not qs.exists():
        return Response({}, status=404)
    serializer = PocketSerializer(qs, many=True)
    return Response(serializer.data, status=200)

@api_view(['GET','POST'])
@authentication_classes([SessionAuthentication])
@permission_classes([IsAuthenticated])
def full_pocket_delete_view(request):
    pockets = Pocket.objects.filter(user=request.user)


    if request.method == 'POST':
        for p in pockets:
            p.delete()
        messages.error(request, "All Pockets Deleted")
        return redirect("/")
    data = {
        "user": str(request.user)
    }

    return Response(data)

# Req to API > Redirect to home
@api_view(['POST', 'GET'])
@authentication_classes([SessionAuthentication])
@permission_classes([IsAuthenticated])
def pocket_delete_view(request, pocket_id, *args, **kwargs):
    qs = Pocket.objects.filter(id=pocket_id)
    if not qs.exists():
        return Response({}, status=404)
    uqs = qs.filter(user = request.user)
    if not uqs.exists():
        return Response({"message":"UnAuthorized Delete"}, status=401)

    if request.method == 'POST':
        
        obj = qs.first()
        obj.delete()
        if str(request.headers.get('referer')) == "https://qsatchel.com/pockets/deepdive":
            messages.error(request, "Trade deleted ")
            return redirect('/pockets/deepdive')

        elif str(request.headers.get('referer')) == "https://qsatchel.com/":
            messages.error(request, "Trade deleted")         
            return redirect('/')
        else: 
            return redirect('/') 

    
    if request.method == 'GET':
        raise Http404
    return Response({"message":"No proper Requests have been Submitted, you may not proceed"}, status=200)


# /api/pockets
@api_view(['GET','POST'])
@permission_classes([IsAuthenticated])
@authentication_classes([SessionAuthentication])
def api_pocket_list_view(request, *args, **kwargs):
    username = request.GET.get('username')
    profile_qs = Profile.objects.filter(user=request.user)
    pqs_first = profile_qs.first()
    
    if request.method == 'POST':
        for value in request.POST.items():    
            choice = value 

        if choice[1] == '-price':
            profile_qs.update(order_matrix='-price')
            return redirect('/')
        elif choice[1] == 'price':
            profile_qs.update(order_matrix = 'price')
            return redirect('/')
        elif choice[1] == 'pocket_time_instance':

templates/pockets/change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

{% if request.user.is_authenticated %}
{% if request.user == pocket.user %}
<br><br>

    <div class="container container-fluid" style="background:none;border:none">

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row g-3">
                <div class="col">
             
                {% comment %} <h6>{{pockets}}
                 </h6> {% endcomment %}


           
    <div class="input-group mb-0">
      <div class="form-control custom-file pointer mx-2 my-2" style="background:none;border:0">
          <label style="border:none;padding:0;background:none:boxShadow:none;cursor:pointer" class="custom-file-upload mr-5">
            
            {% if pocket_image == "firstImageEntry.svg" %}
            <img id="image-preshow" src="/staticmedia/firstImageEntry.svg" class="zoom" style="width:30%;height:30%"/>
            {% else %}
            <img id="image-preshow" src="/staticmedia/{{pocket_image}}" class="zoom shadow shadow-lg" style="width:30%;height:30%;border-radius:15px"/>
            {% endif %}


            <img id="upload-confirmed" src="/staticmedia/bookmark-check-fill.svg" class="zoom filter-green" style="width:35%;height:35%;display:none"/>
            
            
            <h6 id="imageloaded" style="display:none">IMAGE UPLOADED<br><small style="color:grey">Hit checkmark to try again</small></h6>

              <input style="display:none" type="file" name="receipt" class="custom-file-input searchbar" accept="image/*">
          <br><label class="custom-file-label" for="id_receipt" style="font-size:10px;font-weight:bold;font-family:verdana"> NFT / Notes / Receipts</label>
          </label>

          
          <script type="text/javascript" id="script-id_receipt">        
              document.getElementById("script-id_receipt").parentNode.querySelector('.custom-file-input').onchange =  function (e){
                  var filenames = "";

                  $(".custom-file-label").attr("style", "color:#2cac30;font-size:15px;")

                  
                  
                  for (let i=0;i<e.target.files.length;i++){
                      filenames+=(i>0?", ":"")+e.target.files[i].name;
                  }
                  e.target.parentNode.querySelector('.custom-file-label').textContent=filenames;
                  filenames


                  $('#image-preshow').attr('style', "display:none");
                  $('#upload-confirmed').attr('style', "width:30%;height:30%;display:block");
                  
                  $('#imageloaded').attr('style', "display:block;color:#50C44A");

              }        
          </script>  
      </div>
    </div>



  <div class="col darkercard rounded shadow my-2" style="padding:30px;position:relative">


                    {{form.title | as_crispy_field}} <br>
                    <span style="width:200">{{form.summary | as_crispy_field}}</span>
                    {{form.pocket_time_instance | as_crispy_field }} <br>
  </div> 
  <div class="col darkercard rounded shadow my-2" style="padding:30px;position:relative">

                    {{form.exchange | as_crispy_field}}<br>
                    {{form.category | as_crispy_field}} <br>
                    {{form.direction | as_crispy_field}} <br>
  </div> 
                    
              


                  {% comment %} <div class="col" style="position:relative">
                    {{form.profit_or_loss | as_crispy_field}}
                </div> 
                   {% endcomment %}

                
            </div>
        </div>

        <div class="col darkercard rounded shadow my-2" style="padding:30px;position:relative">
          {% if pocket_PnL < 0%}
            <small style="color:crimson">Current PnL<br> {{pocket_PnL}}</small>
          
          {% else %}
          
            <small style="color:#50C44A">Current PnL<br> + ${{pocket_PnL}}</small>
          {% endif %}
          
        
              {{form.price | as_crispy_field}}
                 
            {{form.cost_basis | as_crispy_field}}
        
        
          </div> 
            




            
            
            <br>
            <button type="submit" style="width:40%;z-index:20000;position:fixed;bottom:5px;right:0px;border:none;color:white;background:#50C44A;border-radius:15px" class="btn btn-lg" >UPDATE</button>

        </form> 

                          <form method="POST" class="mb-2" action="/api/pockets/{{pocket.id}}/delete">
                            {% csrf_token %}        
                            <button type="submit" style="border:none;color:white;background:none;border-radius:25px" class="btn btn-danger" >
                              <img src="/staticmedia/dookies.svg" style="width:25px;height:25px" class="filter-red">
                            </button>
                        </form> 

    </div><br>



{% else %}
<meta http-equiv="refresh" content="0; URL=/login" />
{% endif %}
{% endif %}
{% endblock content %}

templates/pockets/listmode.html
{% extends 'base.html' %}
{% block head_title %} DeepDive Trade Analysis{% endblock head_title %}
{% block content %}
{% load humanize %}
<br>

{% if messages %}
<div style='margin:auto;border:none;position:absolute;bottom:5px;left:20px;right:20px;font-weight:bold;padding:10px;z-index:1600;width:350px' 
id="pmessage_container" 
class="darkercard alert fade show container" 
role="alert">
<ul  class="messages" style="margin:auto">
    {% for message in messages %}
    <span{% if message.tags %} class="justify-content-center {{ message.tags }}"{% endif %}>

         <h6 class="mx-2" style=""> {{ message }}   </h6>

    </span>
    {% endfor %}
    </ul>
</div>
{% endif %}

<h2 class="container">  Total Trades : {{pockets_amount}}<br><a style="font-size:15px;color:goldenrod" href="/">
     Insert +</a> 
  
       <!--ALL DELETE ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->

     
           
   
         <button type="button"
         onclick="popUp()"
         style="font-weight:bold;box-shadow:none;font-size:14px;border:none;background:none"
         class="btn btn-outline-danger btn-lg my-2">clear all pockets 
         </button>

 
     
             <div id="popper"
             style="margin:auto;z-index:9000;display:none;position:fixed;padding:20px;right:50px;left:50px"
             data-toggle="popover"
             data-trigger="focus" class="rmvButt darkercard rounded shadow shadow-lg">
                 <form id="bye-form-pock" class="" method="post" action="/api/pockets/full/delete"> {% csrf_token %}
                    <h6 style="opacity:.5" class="container">
                      By clicking Authorize, all pockets created under this account will be deleted from our Database</h6> 
                    <div 
                     style="cursor:pointer;padding:20px;font-size:18px" 
                     id="bye-pock"
                     type="submit" 
                     class="redcard rounded">
                     Authorize  </div>
                     <div class="card close_full_delete" style="cursor:pointer;padding:20px;font-size:18px" > Nevermind</div>
                 </form>
                </div>
     


     <!--ALL DELETE ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->

  
  </h2>

<br><br>
  <div id="pocket_list_format" class="" style="font-size:15px;position:relative;margin:auto;padding:20px"> 
    

  {% if pockets_amount > 0 %}
  
      

          <table class="table container" style="position:relative;border:darkgrey">
            <thead>
              <tr>
        
                <th scope="col">Title</th>
                <th scope="col">Direction</th>
                <th scope="col">Exchange </th>


                <th scope="col">PnL </th>
                <th scope="col">USD Position Size</th>
                <th scope="col">Created</th>
                <th scope="col"></th>
                <th scope="col"></th>
              </tr>
            </thead>
            
            {% for ploop in requested_users_pockets %}
    
              <tr>
                
          
                  <td>{{ploop.title}}</td>
                  {% if ploop.direction == "Long" %}
                    <td style="color:#50C44A">{{ploop.direction}}</td>
                  {% elif ploop.direction == "Short" %}
                  <td style="color:crimson">{{ploop.direction}}</td>
                  
                  {% else %}
                  <td ><h6>{{ploop.direction}}</h6></td>
                
                  {% endif %}

        

                  <td style=""><h6> {{ploop.exchange}} </h6></td>

   

                  {% if ploop.profit_or_loss > 0 %}
                  <td style="color:#50C44A"> +${{ploop.profit_or_loss}} </td>
                  {% elif ploop.profit_or_loss < 0 %}
                  <td style="color:crimson"><h6> ${{ploop.profit_or_loss}} </h6></td>
                  {% else %}
                  <td style=""><h6> ${{ploop.profit_or_loss}} </h6></td>
                  {% endif %}
                  
                {% if ploop.price >= 0 %}
                <td><h6 style="font-weight:bold">${{ploop.price}}</h6></td>
                {% else %}
                <td><h6 style="font-weight:bold;color:crimson">${{ploop.price}}</h6></td>
                {% endif %}
  
                
                <td>{{ploop.timestamp | timesince}} ago</td>
              <td><a href="/pockets/{{ploop.id}}/change"> 
                <img src="/staticmedia/eyes.svg" style="width:20px;height:20px" class="filter-green"/>
              </a></td>
              <td>

                <form action="/api/pockets/{{ploop.id}}/delete" method="POST" style="" data-value="from_deepdive_lobby">
                  {%csrf_token%}
                  <button id="trash_button" name="delmainbtn" style="background:none;cursor:pointer;border:none;width:20px;height:20px">
                    <img src="/staticmedia/dookies.svg" style="width:25px;height:25px" class="filter-red"></button></form>
              </td>

              </tr>


              {% endfor %}
          </table>
    
  
        </div>
  
  {% else %}
  NO TRADES BEING TRACKED
  
  {% endif %}
  

  
  {% endblock content %}

templates/pockets/search.html
{% extends 'base.html' %}
{% block content %}
<div style="color:grey" class="">
<span class="btn-group col">
<button id="peoplebtn" class="btn container" style="cursor:pointer;box-shadow:none" onclick="searchUp()">
<h4 style="font-size:20px;color:grey" class="peepsearch">people</h4></button>
<button id="pocketbtn" class="btn container" style="cursor:pointer;box-shadow:none" disabled="true" onclick="searchUp()">
<h4 style="color:#05e9ff;font-size:20px;" class="pocksearch"> pockets</h4></button><br><br>
</span>
<hr style="width:100%">


 
{% if nogfilter.qs %}
<div id="spocks" style="display:block" data-toggle="popover" data-trigger="focus" class="pocketFade">
{% for n in nogfilter.qs %}
    
        
    
        <span class="card container justify-content-center mb-4 shadow-lg" style="width:300px">
    <a href="/pockets/{{n.id}}/change">
    <small style="color:grey;font-size:9px">pocket name: </small>
        {{n.title}}<br>
    <small style="color:grey;font-size:9px">category: </small>
        {{n.category}}<br>
        
        {% if n.price < 0 %}
            <small id="search_price" style="color:crimson">
            {{n.price}} {{n.currency}}</small>
        {% else %}
            <small id="search_price" style="color:#50C44A">
            {{n.price}} {{n.currency}}</small>
        {% endif %}

        
        
         <hr>
        <p style="font-size:10px">
        
        <small class="container" style="color:grey">description: </small>{{n.summary}}</p> 
        <p class="container" style="color:grey;font-size:10px"> created {{n.pocket_time_instance | timesince}} ago </p>
    </a>    
        </span>
    
    

{% endfor %}
{% else %}
<span class="pocketinform">
      <h6 class="container container-fluid" style="color:crimson">
        <img src="/staticmedia/nothing.svg" class="filter-red" style="width:45px;height:45px;position:relative"/>
        <strong>{{query}} </strong> ... was not found in the Database  </h6>
<span>
{% endif %}
</div>

        <div id="people" style="display:none" data-toggle="popover" data-trigger="focus" class="peopleFade">
            {% if profilter.qs %}
            {% for u in profilter.qs %}
                
                    
                
                    <span class="card container justify-content-center mb-4 shadow-lg" style=";position:relative;width:300px">
                <a href="/profiles/{{u}}">
                
                

                        <p> 
                    <img src="/staticmedia/superanons.png" style="opacity:.2;position:absolute;right:1;bottom:1;width:50px;height:50px"/>

                        @{{u}} </p>
                        <img class="my-2" src="/staticmedia/{{u.avatar}}" style="float:right;border-radius:50%;width:90px;height:90px"/>
                
                        {% if u.bio %}
                            <p style="font-size:10px">{{u.bio}}</p>
                        {% else %}
                            <p style="color:grey"> this users Bio is Empty </p>
                        {% endif %}
                        </a>

                    </span>
                
                

            {% endfor %}
            {% else %}
                <h6 class="container container-fluid" style="color:crimson">
                  <img src="/staticmedia/nothing.svg" class="filter-red" style="width:45px;height:45px;position:relative"/>
                  <strong>{{query}}</strong> ...  was not found in the Member Database</h6>
            {% endif %}
        </div>
</div>

     
{% endblock content %}