pockets/urls.py
from django.urls import path


from pockets.views import (
    pocket_delete_view,
    pocket_detail_view,
    api_pocket_list_view,
    pocket_create_view,
    full_pocket_delete_view,
 
)
# has api/pockets before each endpoint
urlpatterns = [
    path('full/delete', full_pocket_delete_view, name="full pocket del"),
    path('<int:pocket_id>/delete', pocket_delete_view),
    path('<int:pocket_id>', pocket_detail_view),
    path('pocketcreate', pocket_create_view),
    path('', api_pocket_list_view),   


]

profiles/urls.py
from django.urls import path
from .views import (
    profile_detail_view,
    analyze_view,
    allocation_view,  
    profile_update_view, 
    profile_detail_api_view,
    updateTheme,
    profile_followers_view,
    profile_following_view,
    connection_ToggleEP,
    # unfollow_ToggleEP
    
)

urlpatterns = [
    path('api/', profile_detail_api_view, name="papi"),
    path('<str:username>/', profile_detail_view),
    path('analyze/charts', analyze_view),
    path('analyze/charts/allocation', allocation_view),

    path('<str:username>/followers/', profile_followers_view),
    path('<str:username>/following/', profile_following_view),
    
    # For the Follow/Unfollow System follows the follwoing , 
    # the the subject being Follow/Unfollowed comes before the member (actor) performing the action
    # in this case, request.user is often the actor
    path('<str:subject>/follow_activation/<str:actor>/', connection_ToggleEP),
    # path('<str:username>/unfollow_activation/<str:username>/', unfollow_ToggleEP),


    path('update_theme', updateTheme, name='papi_update_theme'),
    path('<str:username>/follow_toggle_activation', updateTheme, name='follow_toggle_url'),
    
    path('edit', profile_update_view),
]

profiles/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save

from django.core.cache import cache 
from django.conf import settings
from allauth.socialaccount.adapter import DefaultSocialAccountAdapter
from allauth.account.adapter import DefaultAccountAdapter


import datetime
import random
import string

User = settings.AUTH_USER_MODEL 


class MyAccountAdapter(DefaultAccountAdapter):

    def get_login_redirect_url(self, request):
        path = "/"
        return path.format(username=request.user.username)
    
    def get_email_confirmation_redirect_url(self, request):
      path = "/oauth/email/"
      return path


class CustomSocialAccountAdapter(DefaultSocialAccountAdapter):

    def populate_user(self, request, sociallogin, data):
        user = super().populate_user(request, sociallogin, data)
        allowed_chars = ''.join((string.ascii_letters, string.digits))
        random_aplhanumeric = ''.join(random.choice(allowed_chars) for _ in range(15))
        user.username = (random_aplhanumeric).upper()
        return user

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    followers = models.ManyToManyField(User, related_name='followers', blank=True)
    following = models.ManyToManyField(User, related_name='following',blank=True) 
    avatar = models.ImageField(upload_to='avatars/%Y/%m/%d/', default='anonimage.png', null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
  
    bio = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    style_value = models.CharField(max_length=200, null=True)
    satchel = models.DecimalField(max_digits=10,decimal_places=2, default=0.0)
    pos_satchel = models.DecimalField(max_digits=10,decimal_places=2, default=0.0)
    neg_satchel = models.DecimalField(max_digits=10,decimal_places=2, default=0.0)
    is_online = models.BooleanField(default=False)


    order_matrix = models.CharField(max_length=70, null=True, blank=True, default='-timestamp')


    def __str__(self):
        return self.user.username



    def user_did_save(sender, instance, created, *args, **kwargs):
        Profile.objects.get_or_create(user=instance)
        if created:
            Profile.objects.get_or_create(user=instance)

    post_save.connect(user_did_save, sender=User)

profiles/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Profile

from crispy_forms.helper import FormHelper
from django.core.files.base import ContentFile

User = get_user_model()

#affects user update form





class ProfileForm(forms.ModelForm):
    last_name = forms.CharField(required=False)
    username = forms.CharField(required=False)
    first_name = forms.CharField(required=False)
    email = forms.CharField(required=False)
    satchel = forms.DecimalField(required=False)
    avatar = forms.ImageField(required=False)
    
    class Meta:
        model = Profile
        fields = ['satchel','last_name','first_name', 'username','location', 'avatar', 'bio','email']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = True
        for field in ProfileForm.Meta.fields:
            self.fields[field].label = False

profiles/views.py
import json
from decimal import Decimal
from fractions import Fraction

from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.signals import user_logged_in, user_logged_out
from django.dispatch import receiver  
# created
from .models import Profile
from pockets.models import Pocket
from .forms import ProfileForm
from .serializers import SharedProfileSerializer
# RESTAPI
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
# from rest_framework import authentication, permissions
from rest_framework import authentication, permissions
from rest_framework.authentication import SessionAuthentication
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.views import APIView

from allauth.account.models import EmailAddress
from django.views.decorators.http import require_http_methods
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.http import Http404
from django.conf import settings
from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from allauth.account.adapter import DefaultAccountAdapter



User = get_user_model()





def nonauto_login_view(request, *args, **kwargs):


    form = AuthenticationForm(request, data=request.POST or None)
    if form.is_valid():
        user_ = form.get_user()
        login(request, user_)

        return redirect("/profiles/analyze/charts")

    context = {
        "form": form,
    }
    
    return render(request, "pages/nonautologin.html", context)


def error_404_view(request, exception):
    return render(request, "404.html")

@receiver(user_logged_in)
def got_online(sender, user, request, **kwargs):    
    user.profile.is_online = True
    user.profile.save()

@receiver(user_logged_out)
def got_offline(sender, user, request, **kwargs):   
    user.profile.is_online = False
    user.profile.save()


def profile_detail_view(request, username, *args, **kwargs): # template for profile detail
    # get profile
    if not request.user.is_authenticated:
        messages.error(request, " Please Login")
        return redirect("/oauth/login")
    qs = Profile.objects.filter(user__username=username)
    if not qs.exists():
        raise Http404

    qsone = qs.first()

    actorqs = Profile.objects.filter(user__username=request.user)
    actorqsone = actorqs.first()

    user_model = User.objects.filter(username=username)
    user_pockets = Pocket.objects.filter(user=request.user)

    
    followers = qsone.followers.all()
    following = qsone.following.all()


    if username in actorqsone.following.all():
      button_action = "UNFOLLOW"
    elif request.user in qsone.followers.all():
      button_action = "UNFOLLOW"
    else:
      button_action = "FOLLOW "
  


    
    djangouser = User.objects.filter(username = username).first()
     
    allauth_email = EmailAddress.objects.filter(user=djangouser.id) # allauth ...  user = the ID 
    context = {"profiles":qs,
    "bus_email": user_model.first().email, 
    "pockets_amount": user_pockets.count(),
    "qsone": qsone,
    "button_action": button_action, 
  
    # "following_avatar_bin": f_avatar_bin,
    "followers_count": followers.count(),
    "following_count":following.count(),
    "username":username, 
    "satchel": qsone.satchel, 
    "pos_satchel": qsone.pos_satchel,
    "neg_satchel": qsone.neg_satchel,
    "oauth_email": allauth_email
    }
    return render(request, "profiles/detail.html", context)

def analyze_view(request, *args, **kwargs): # template for profile detail

    if not request.user.is_authenticated:
        messages.error(request, " Please Login")
        return redirect("/oauth/login")
    qs = Profile.objects.filter(user__username=str(request.user))
    if not qs.exists():
        raise Http404

    qsone = qs.first()


    user_model = User.objects.filter(username=str(request.user))
    user_pockets = Pocket.objects.filter(user=request.user)
    pocket_average = Decimal(0.0)

    satchel = Decimal(0.0) #sum 
    pos_satchel = Decimal(0.0)
    neg_satchel = Decimal(0.0)

    WINS = Decimal(0.0)
    LOSSES = Decimal(0.0)

    bin = []


    for p in user_pockets:
         
        
        if p.currency == "USD":
            satchel += p.price / 1

        if p.price < 0:
            neg_satchel += p.price
            LOSSES += 1 
        elif p.price >= 0:
            pos_satchel += p.price
            WINS += 1
        bin.insert(0, p.price)
        

    if len(bin) > 0:
        pocket_average = satchel/len(bin) # Total Sum / Length of Entire Pocket Array
    elif len(bin) <= 0:
        pocket_average = 0.00
    

    context = {
    "profiles":qs,

    "WINS": WINS,
    "LOSSES": LOSSES,

    "followers_am": qsone.followers.count(),

    "pocketsamount": user_pockets.count(),
    "following_am": qsone.following.count(),
    "bus_email": user_model.first().email, 
    "pockets_amount": user_pockets.count(),

    "qsone": qsone,
    "username":str(request.user), 
    "satchel": round(satchel, 2),

    "pos_satchel": round(pos_satchel , 2),
    "neg_satchel": round(neg_satchel, 2),
    "avg_satchel": round(pocket_average, 2),
    
    }
    return render(request, "profiles/analyze.html", context)


def allocation_view(request, *args, **kwargs): # template for profile detail

    if not request.user.is_authenticated:
        messages.error(request, " Please Login")
        return redirect("/oauth/login")
    qs = Profile.objects.filter(user__username=str(request.user))
    qsone = qs.first()
    user_pockets = Pocket.objects.filter(user=request.user)
    
    if not qs.exists() or not user_pockets.exists():
        raise Http404

    absoluteSatchel = Decimal(0.0) # 
    positiveWeights = []
    negativeWeights = []

    positiveWeightTotal = Decimal(0.0)
    negativeWeightTotal = Decimal(0.0)

    for proxy in user_pockets:
        absoluteSatchel += abs(proxy.price)
    for p in user_pockets:
        if p.price >= 0:      
            positiveWeights.insert(0, (abs(p.price)/int(absoluteSatchel))*100)  
        elif p.price < 0:
            negativeWeights.insert(0, (abs(p.price)/int(absoluteSatchel))*100)
    for posW in positiveWeights:
        positiveWeightTotal += posW 
    for negW in negativeWeights:
        negativeWeightTotal += negW


    context = {
    "profiles":qs,
    "pockets_amount": user_pockets.count(),
    "qsone": qsone,
    "username":str(request.user), 
    "satchel": round(qsone.satchel, 2),
    "pos_satchel": qsone.pos_satchel,
    "neg_satchel": qsone.neg_satchel,
    "positiveWeightTotal": round(positiveWeightTotal, 5),
    "negativeWeightTotal": round(negativeWeightTotal, 5)
    }
    return render(request, "profiles/allocation.html", context)



def profile_update_view(request, *args, **kwargs): # template for profile remodel
    if not request.user.is_authenticated:
        raise Http404
    profileQuery = Profile.objects.all()
    # pquery_obj = profileQuery.first()
    userQ = profileQuery.filter(user=request.user).first()

    user = request.user
    user_data = {
        "first_name": user.first_name,
        "username": user.username,
        "last_name": user.last_name,
        "email": user.email
    }
    my_profile = user.profile
    post_data = request.POST or None 
    file_data = request.FILES or None
    form = ProfileForm(post_data, file_data, instance=my_profile, initial=user_data)
    if form.is_valid():
        profile_obj = form.save(commit=False)
        first_name = form.cleaned_data.get('first_name')
        last_name = form.cleaned_data.get('last_name')
        email = form.cleaned_data.get('email')
        # username = form.cleaned_data.get('username')
        
        # solution
        avatar = form.cleaned_data.get('avatar')

        user.first_name = first_name
        user.last_name = last_name
        #solution

        user.avatar = avatar

        user.email = email

        user.save()
        profile_obj.save()
        messages.success(request, "Changes have been made")

        return redirect('/profiles/edit')
    context = {
        "form": form,
        "mainuser": userQ,
        "profilePicture": userQ.avatar,
        "profiles":profileQuery,

    }
    return render(request, "profiles/remodel.html", context)

@api_view(['GET','POST'])
@permission_classes([IsAuthenticated])
@authentication_classes([SessionAuthentication])
def profile_detail_api_view(request, *args, **kwargs): # profile Detail API endpoint
    # profile query search
    qs = Profile.objects.filter(user__username=request.user.username)
    if not qs.exists():
        return Response({"detail": "Sorry, That Is Not a Known Member"}, status=404)
    profile_obj = qs.first()

    serializer = SharedProfileSerializer(instance=profile_obj, context={"request": request})

    return JsonResponse(serializer.data, status=200)

def updateTheme(request): # CSS toggle Endpoint
    if request.method == 'GET':
        raise Http404
    elif request.method == 'POST':
        data = json.loads(request.body)
        theme = data['theme']
        profile = Profile.objects.filter(user = request.user)
        profile.update(style_value = theme)

    return JsonResponse('Updated', safe=False)





# follow / unfollow system________________________________________



def profile_followers_view(request, username, *args, **kwargs):


    if not request.user.is_authenticated:
        messages.error(request, " Please Login")
        return redirect("/oauth/login")
    qs = Profile.objects.filter(user__username=username)

    if not qs.exists():
        raise Http404
    qsone = qs.first()
    
    followers = qsone.followers.all()

templates/profiles/allocation.html
{% extends 'base.html' %}
{% block head_title %}ALLOCATION CHART{% endblock head_title %}

{% block content %}
{% load humanize %}


{% if username|cut:" " == request.user|cut:" " %}
        {% if pockets_amount > 0 %}
<center class="card" style="padding:2px">          

          {% if satchel < 100000000 %}
          <canvas id="percentChart" style="position:relative;height:60vh;width:80vw" class="my-5"></canvas>
          {% else %}
          
{% comment %} STUFF GOES HERE FOR WHEN OVER 100 MILLION {% endcomment %}

          {% endif %}

<div class="darkercard rounded shadow" style="padding:10px;width:400px">{{positiveWeightTotal}}% of your trades are in Profit</div>

<br>

<div class="darkercard rounded shadow" style="padding:10px;width:400px">{{negativeWeightTotal}}% of your trades are at a Loss</div>


     <br>
     
<div class="rounded padTipPOP container container-fluid" id="padTipclose" style="font-size:15px;cursor:pointer;background:#8dbcc7;border-radius:0%;display:none;z-index:4500;position:fixed;padding:15px;width:350px;top:5px;right:5px;color:white"> 

            The value of each Pocket (Gain or Loss) affects its Magnitude with respect to the absolute value Sum 
            These results are derived after the conversion of each input into United States Dollar <br>
                        <a style="position:relative;" href="https://github.com/hug0sh0t/QSATCHEL8.0#how-the-percentage-allocation-doughnut-pad-engine-was-made">
              <img src="/staticmedia/iconmonstr-github-1.svg" class="filter-white" style="width:50px;height:50px"/>
            </a>

</div>




<div style="position:fixed;right:10px;bottom:10px">
<img src="/staticmedia/shout.svg" id="manualshowpad" class="filter-grey" style="margin-top:50px;cursor:pointer;border-radius:25px;width:25px;height:25px"/> 
</div>




</center>
        {% endif %}  
{% endif %}  
<script>



    const pocketendpoint = '/api/chart'
    var defaultData = []
    var labels = [];
    




   // Allocation Chart Handle +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


        $.ajax({
        method:"GET",
        url: pocketendpoint,
        dataType: "json",
        contentType: "application/json",
        success: function(data) {
            labels = data.labels
            satchel_sent = data.satchel
            defaultData = data.default
            dynamicPreConversionPercentArray = data.dynamicPreConversionPercentArray
            dynamicRBGArray = data.dynamicRBGArray
            hoverdynamicRBGArray = data.hoverdynamicPriceToColorArray


            var ctx = document.getElementById('percentChart').getContext('2d');
  
            var tester = " Converted Sum  $"
            var myChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: labels,
                    datasets: [{
                        label: labels,

                        data: dynamicPreConversionPercentArray,
                        backgroundColor: dynamicRBGArray,
                        borderColor: dynamicRBGArray,
                        hoverBorderColo: hoverdynamicRBGArray,
                        borderWidth: 1,
                        offset: 1,
                        hoverBorderWidth: 8,
                        

                    }],
                    

                },
                options: {
                 
                    elements: {
                        center: {
                          text: '$ '+satchel_sent + ' USD',
                          color:  (setTheme == 'light.css') ? '#24292d' : '#fff', // Default is #000000
                          fontStyle: 'Arial',
                          sidePadding: 20, // Default is 20 (as a percentage)
                          minFontSize: 20, // Default is 20 (in px), set to false and text will not wrap.
                          lineHeight: 25 // Default is 25 (in px), used for when text wraps
                        }
                    },
        
 
                    scales: {
                        yAxes: [{
                            gridLines: {
                              display:false
                            },
                            ticks: {
                                beginAtZero: true,
                                callback: function(value) { },
                            }
                        }],
                        xAxes: [{
                            gridLines: {
                              display:false
                            },
                            ticks: {
                                callback: function(value) { },
                                
                                beginAtZero: true
                               }                        
                        }],

                    },

                    legend: {
                        display: false
                    },
                    title: {
                        display: true,
                        text: 'Weight Allocation (%)'
                    },

                    interaction: {
                        mode: 'point'
                    },
                    tooltips: {
                            // Disable the on-canvas tooltip
                            enabled: true,
                            backgroundColor: (setTheme == 'light.css') ? '#000000' : '#24292d',


                            xPadding: 30,
                            yPadding: 30,
                            displayColors: false,
                            callbacks: {
                                label: function(tooltipItem, data) {
                                    return data['datasets'][0]['data'][tooltipItem['index']] + ' %';
                                },
                     

                            title: function(tooltipItem, data) {
                                return data['labels'][tooltipItem[0]['index']];
                            },
                                // label: function(tooltipItems, data) { return tooltipItems.yLabel ;},
                                labelTextColor: function(context) {return (setTheme == 'dark.css') ? '#fff':'#fff'},
                            }
                  
                    }
                }    
            })
        },
        error: function(error_data) {
            console.log("error")
            console.log(error_data)
        }
    })
   // allocation Chart Handle +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++




Chart.pluginService.register({
  beforeDraw: function(chart) {
    if (chart.config.options.elements.center) {
      // Get ctx from string
      var ctx = chart.chart.ctx;

      // Get options from the center object in options
      var centerConfig = chart.config.options.elements.center;
      var fontStyle = centerConfig.fontStyle || 'Arial';
      var txt = centerConfig.text;
      var color = centerConfig.color || '#000';
      var maxFontSize = centerConfig.maxFontSize || 75;
      var sidePadding = centerConfig.sidePadding || 20;
      var sidePaddingCalculated = (sidePadding / 100) * (chart.innerRadius * 2)
      // Start with a base font of 30px
      ctx.font = "30px " + fontStyle;

      // Get the width of the string and also the width of the element minus 10 to give it 5px side padding
      var stringWidth = ctx.measureText(txt).width;
      var elementWidth = (chart.innerRadius * 2) - sidePaddingCalculated;

      // Find out how much the font can grow in width.
      var widthRatio = elementWidth / stringWidth;
      var newFontSize = Math.floor(30 * widthRatio);
      var elementHeight = (chart.innerRadius * 2);

      // Pick a new font size so it will not be larger than the height of label.
      var fontSizeToUse = Math.min(newFontSize, elementHeight, maxFontSize);
      var minFontSize = centerConfig.minFontSize;
      var lineHeight = centerConfig.lineHeight || 25;
      var wrapText = false;

      if (minFontSize === undefined) {
        minFontSize = 20;
      }

      if (minFontSize && fontSizeToUse < minFontSize) {
        fontSizeToUse = minFontSize;
        wrapText = true;
      }

      // Set font settings to draw it correctly.
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      var centerX = ((chart.chartArea.left + chart.chartArea.right) / 2);
      var centerY = ((chart.chartArea.top + chart.chartArea.bottom) / 2);
      ctx.font = fontSizeToUse + "px " + fontStyle;
      ctx.fillStyle = color;

      if (!wrapText) {
        ctx.fillText(txt, centerX, centerY);
        return;
      }

      var words = txt.split(' ');
      var line = '';
      var lines = [];

      // Break words up into multiple lines if necessary
      for (var n = 0; n < words.length; n++) {
        var testLine = line + words[n] + ' ';
        var metrics = ctx.measureText(testLine);
        var testWidth = metrics.width;
        if (testWidth > elementWidth && n > 0) {
          lines.push(line);
          line = words[n] + ' ';
        } else {
          line = testLine;
        }
      }

      // Move the center up depending on line height and number of lines
      centerY -= (lines.length / 2) * lineHeight;

      for (var n = 0; n < lines.length; n++) {
        ctx.fillText(lines[n], centerX, centerY);
        centerY += lineHeight;
      }
      //Draw text in center
      ctx.fillText(line, centerX, centerY);
    }
  }
});

</script>

{% endblock content %}

templates/profiles/remodel.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}
  Remodeling
{% endblock head_title%}
{% block content %}

{% if messages %}
<br><br><center><div style='width:50%;position:fixed;padding:10px;left:0px;right:0px;top:100px;z-index:9000;background-color:#50C44Aab' 
id="pmessage_container" 
class="shadow shadow-lg alert rounded fade show container" 
role="alert">
<ul  class="messages">
    {% for message in messages %}
    <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
      <center>
      <h6 style="font-weight:bold;color:white">
        {{ message }}
      </h6>
      </center>
    </span>
    </div>
    {% endfor %}
  </ul></center>
{% endif %}
<br>
<div>
<div class='remod_form mt-5 container container-fluid'>
  <div>
  
  <center>


    <form style="position:relative"  method='POST' enctype='multipart/form-data'>
        {% csrf_token %}








      <div id="div_id_avatar" class="form-group">
      <div class=" mb-2">


      <div class="input-group mx-5 mb-2">
          
          <div class="mx-4 pointer">
              <span class="text-break" style="flex-grow:1;min-width:0">
              
              
              </span>
              
              <span class="align-self-center ml-5">
                  <span class="custom-control custom-checkbox">

                  </span>
              </span>
          
          </div>
      </div>
      <div class="input-group mb-0">


        <div class="form-control custom-file pointer mx-2 my-2" style="background:none;border:0">
            <label style="border:none;padding:0;background:none:boxShadow:none;cursor:pointer" class="custom-file-upload mr-5">
              <img id="image-preshow" src="/staticmedia/{{profilePicture}}" class="border" style="border-radius:50%;width:75px;height:75px"/>

              
              <h6 id="imageloaded" style="display:none">
                <img id="upload-confirmed" src="/staticmedia/bookmark-check-fill.svg" class="zoom filter-green" style="width:35%;height:35%;display:none"/>
                IMAGE UPLOADED<br><small style="color:grey">Hit checkmark to try again</small></h6> 
              
              <input style="display:none" type="file" name="avatar" class="custom-file-input searchbar" accept="image/*">
            <br><label class="custom-file-label" for="id_avatar" style="font-size:10px;font-weight:bold;font-family:verdana">change your avatar </label>
            </label>

            
            <script type="text/javascript" id="script-id_avatar">        
                document.getElementById("script-id_avatar").parentNode.querySelector('.custom-file-input').onchange =  function (e){
                    var filenames = "";
                    $(".custom-file-label").attr("style", "color:#2cac30;font-size:15px;")

                    for (let i=0;i<e.target.files.length;i++){
                        filenames+=(i>0?", ":"")+e.target.files[i].name;
                    }
                    e.target.parentNode.querySelector('.custom-file-label').textContent=filenames;
                    filenames
       
                    $('#image-preshow').attr('class', "zoom");

                    $('#imageloaded').attr('style', "display:block;color:#50C44A");
                    $('#avatarTip').attr('style', "display:block");    
                    $('#image-preshow').attr('style', "display:none");
                    $('#upload-confirmed').attr('style', "width:30%;height:30%;display:block");
      
                }        
            </script>
        </div>
      

      </div>
    </div>



<div class="input-group" style="position:relative">
<h6 style="opacity:.7">username :{{request.user.username}}</h6>
          <h6 class="mx-4">first name
          {{ form.first_name | as_crispy_field }}</h6>
          <h6 class="mx-4">last name
          {{form.last_name | as_crispy_field}}</h6>
           <h6 class="mx-4">location
           {{form.location | as_crispy_field}}</h6>

</div><br>








         
      <h6><br>
           <div class="myDIV" style="left:0px;right:0px;position:relative">
           <span>
                <button  
                type="button"      
                onclick="toggleStyle('dark.css')" 
                style="border:none;background:none;box-shadow:none" 
                class="darktoggle btn btn-sm "> 
                    {% comment %} <img alt="darkness" src="/staticmedia/moon.svg" style="width:50px;height:50px" /> {% endcomment %}
                        <div class="card shadow shadowlg" style="padding:20px;border:none"><strong style="color:#00000">DARK MODE</strong></div>

                  </button>
            
                  
                    <button
                    type="button"
                    style="border:none;background:none;box-shadow:none" 
                    onclick="toggleStyle('light.css')" 
                    class="lighttoggle btn btn-sm btn-outline-dark"> 
                        <div class="card shadow shadowlg" style="padding:20px;border:none"><strong style="color:#fff">LIGHT MODE</strong></div>
                    </button>
              </div><h6 class="hide" style="font-size:9px;position:relative">
                toggle scenery </h6>
              
            </span>
    </div><br><br></h6>




    <h6>About You <br>{{form.bio|as_crispy_field}}</h6>



    <span class="btn-group col container container-fluid" style="position:relative">

        <button type='submit' style="font-weight:bold;font-size:15px;border:none;background:none;box-shadow:none" class='myDIV btn-control btn btn-outline-success btn-lg btn-block'>
          SAVE CHANGES
        </button>
    </span>
    </form>
  </center>
      
 </div>
 <br><br><br><br>
</div>
</div>
{% endblock content %}